- README.md
same for `stable9` 😉 @MorrisJobke 
ToDo:
> [stable9] Update README.md

- doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php
needed for the CI stuff 🙈 (and was also merged upstream https://github.com/doctrine/dbal/pull/2422 )
> fix mysql driver error handling

- composer.json
- composer.lock
- composer/installed.json
- guzzlehttp/guzzle/LICENSE
- guzzlehttp/guzzle/src/Client.php
- guzzlehttp/guzzle/src/ClientInterface.php
- guzzlehttp/guzzle/src/Event/Emitter.php
- guzzlehttp/guzzle/src/Message/AbstractMessage.php
- guzzlehttp/guzzle/src/Message/MessageFactory.php
Ref https://nextcloud.com/httpoxy-can-affect-nextcloud-get-your-update-now/ which has been hotpatched in the server
> [master] Update GuzzleHTTP to 5.3.1 in Git

- composer.json
- composer.lock
- composer/autoload_classmap.php
- composer/autoload_static.php
- composer/installed.json
- symfony/process/ExecutableFinder.php
- symfony/process/InputStream.php
- symfony/process/LICENSE
- symfony/process/PhpExecutableFinder.php
- symfony/process/PhpProcess.php
- symfony/process/Pipes/AbstractPipes.php
- symfony/process/Pipes/PipesInterface.php
- symfony/process/Pipes/UnixPipes.php
- symfony/process/Pipes/WindowsPipes.php
- symfony/process/Process.php
- symfony/process/ProcessBuilder.php
- symfony/process/ProcessUtils.php
> Bump symfony/process

- composer.json
> :speak_no_evil:

- swiftmailer/swiftmailer/lib/classes/Swift/Transport/MailTransport.php
Signed-off-by: Lukas Reschke <lukas@statuscode.ch>
> [stable11] Swift transport

- swiftmailer/swiftmailer/lib/classes/Swift/Transport/MailTransport.php
Signed-off-by: Lukas Reschke <lukas@statuscode.ch>
> [stable10] Swift transport

- composer.lock
- composer/ClassLoader.php
- composer/autoload_real.php
- composer/installed.json
- swiftmailer/swiftmailer/lib/classes/Swift/Transport/MailTransport.php
> Restore swiftmailer to original package

- patches.txt
- sabre/dav/lib/DAV/Server.php
Early port of https://github.com/fruux/sabre-dav/pull/982/files which also has a unit test showing the issue.
Fix https://github.com/nextcloud/server/issues/5543
Would be nice if this is also backported to 12 🤷‍
> Fix infinite propfinds reporting files as directories

- patches.txt
- sabre/dav/lib/DAV/Server.php
> [stable12] Fix infinite propfinds reporting files as directories

- patches.txt
- rackspace/php-opencloud/lib/OpenCloud/ObjectStore/Resource/AbstractResource.php
- sabre/xml/lib/Service.php
Required for https://github.com/nextcloud/server/pull/5776
> Fix phpdocs

- composer.json
- composer.lock
- composer/include_paths.php
- composer/installed.json
- pear/archive_tar/Archive/Tar.php
- pear/archive_tar/package.xml
Required for https://github.com/nextcloud/server/pull/5791
Signed-off-by: Lukas Reschke <lukas@statuscode.ch>
> Bump Archive_Tar from 1.4.1 to 1.4.3

- patches.txt
- sabre/xml/lib/Deserializer/functions.php
For https://github.com/nextcloud/server/pull/6218
> Prevent infinite loop in sabre/xml

- patches.txt
- sabre/xml/lib/Deserializer/functions.php
> [stable11] Prevent infinite loop in sabre/xml

- mcnetic/zipstreamer/src/ZipStreamer.php
- patches.txt
> [stable11] Patch ZipStreamer to fix directory downloads

- composer.json
- composer.lock
- composer/installed.json
- patches.txt
- php-opencloud/openstack/README.md
- php-opencloud/openstack/src/Common/Resource/AbstractResource.php
- php-opencloud/openstack/src/ObjectStore/v1/Models/StorageObject.php
Signed-off-by: Robin Appelman <robin@icewind.nl>
> update php-opencloud/openstack to 3.0.4

- composer.json
- composer.lock
- composer/ClassLoader.php
- composer/autoload_real.php
- composer/installed.json
- icewind/searchdav/src/DAV/SearchHandler.php
Signed-off-by: Robin Appelman <robin@icewind.nl>
> update icewind/searchdav to 1.0.1

- composer.json
> Set a platform so we always support our minimal php version

- composer.json
- composer.lock
- composer/installed.json
- symfony/process/ExecutableFinder.php
- symfony/routing/composer.json
> Bump symfony deps to 3.4.12

- composer.json
- composer.lock
- composer/installed.json
- symfony/console/Application.php
- symfony/console/Command/Command.php
- symfony/console/Formatter/OutputFormatterStyle.php
- symfony/console/Helper/SymfonyQuestionHelper.php
- symfony/console/Helper/Table.php
- symfony/console/Input/ArgvInput.php
- symfony/console/Input/InputArgument.php
- symfony/console/Input/InputDefinition.php
- symfony/console/Input/InputInterface.php
- symfony/console/Input/InputOption.php
- symfony/console/Output/StreamOutput.php
- symfony/process/PhpProcess.php
- symfony/process/Process.php
- symfony/routing/Loader/YamlFileLoader.php
- symfony/routing/RouteCollectionBuilder.php
- symfony/translation/Catalogue/AbstractOperation.php
- symfony/translation/Dumper/CsvFileDumper.php
> Bump symfony to 3.4.16

- composer.json
- composer.lock
- composer/installed.json
- symfony/console/Application.php
- symfony/console/Command/Command.php
- symfony/console/Helper/QuestionHelper.php
- symfony/console/Input/InputArgument.php
- symfony/console/Input/InputDefinition.php
- symfony/console/Input/InputInterface.php
- symfony/console/Input/InputOption.php
- symfony/console/Question/Question.php
- symfony/process/InputStream.php
- symfony/process/Process.php
- symfony/process/ProcessBuilder.php
- symfony/routing/Matcher/Dumper/StaticPrefixCollection.php
- symfony/routing/Route.php
- symfony/translation/Catalogue/AbstractOperation.php
- symfony/translation/Dumper/MoFileDumper.php
- symfony/translation/Extractor/PhpStringTokenParser.php
> Bump symfony 3.4.17

- doctrine/dbal/lib/Doctrine/DBAL/SQLParserUtils.php
- patches.txt
https://github.com/doctrine/dbal/pull/3104
> Fix named parameter detection on SQLite

- composer.json
> Update php platform to 7.1 so we get more bumps

- sabre/dav/lib/CalDAV/ICSExportPlugin.php
- sabre/dav/lib/DAV/CorePlugin.php
- sabre/vobject/lib/Component/VCard.php
- sabre/vobject/lib/FreeBusyGenerator.php
Copied some patches from all the sabre repos.
Alternatively we can upgrade to 4.0.0-alpha*
This should then fix the tests of the activity app:
https://github.com/nextcloud/activity/pull/318#pullrequestreview-177884175
> Try to support 7.3 for DAV

- composer.json
- composer.lock
- composer/installed.json
- icewind/streams/src/CallbackWrapper.php
> Bump icewind/streams to 0.7.0

- composer.json
- composer.lock
- composer/installed.json
- icewind/streams/src/CallbackWrapper.php
> Bump icewind/streams to 0.7.1

- sabre/vobject/lib/Property/ICalendar/DateTime.php
> Fix sabre return type

- composer.json
- composer.lock
… in order to use it in server.
> Explicitly require symfony-event-dispatcher-contracs

- composer.json
> Minimum php is 7.2

- .github/workflows/composer.yml
- README.md
- composer.json
Just so that we don't have to do this manually :)
> Add composer vendor script

- composer.json
- composer.lock
It was already there as a sub-dep of Pimple or so, so no big changes necessary.
For https://github.com/nextcloud/server/pull/21809
> Install the PSR-11 container

- composer.json
- composer.lock
- composer/installed.json
- stecman/symfony-console-completion/src/CompletionCommand.php
- stecman/symfony-console-completion/src/CompletionContext.php
- stecman/symfony-console-completion/src/CompletionHandler.php
- stecman/symfony-console-completion/src/HookFactory.php
> [stable19] Bump stecman/symfony-console-completion from 0.8.0 to 0.11.0

- composer.json
... and wait for dependabot ;)
> Permit non breaking updates for archive_tar

- composer.lock
- composer/installed.json
- sabre/xml/.gitignore
- sabre/xml/CHANGELOG.md
- sabre/xml/composer.json
- sabre/xml/lib/Reader.php
- sabre/xml/lib/Service.php
- sabre/xml/lib/Version.php
Backport of https://github.com/nextcloud/3rdparty/pull/527
> [stable19] Update sabre/xml to fix XML parsing errors

- composer.json
- composer.lock
- composer/InstalledVersions.php
- composer/autoload_psr4.php
- composer/autoload_static.php
- composer/installed.json
- composer/installed.php
The 7.2 min might have held some Dependabot bumps back :worried:
> Require php7.3 or php8

- composer.lock
- composer/InstalledVersions.php
- composer/installed.json
- composer/installed.php
Yay for no actual code changes.
> Invite the sabre family to the php8 party

- composer/ClassLoader.php
- composer/InstalledVersions.php
- composer/installed.json
- composer/installed.php
- composer/package-versions-deprecated/src/PackageVersions/Versions.php
Signed-off-by: Carl Schwan <carl@carlschwan.eu>
> Update composer generated files to 2.1.8

- .github/workflows/composer.yml
- composer.json
- composer.lock
- composer/installed.json
- composer/installed.php
- composer/package-versions-deprecated/src/PackageVersions/Versions.php
- pimple/pimple/src/Pimple/Container.php
- pimple/pimple/src/Pimple/Psr11/ServiceLocator.php
- pimple/pimple/src/Pimple/ServiceIterator.php
- pimple/pimple/src/Pimple/ServiceProviderInterface.php
Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>
> Bump pimple/pimple to 3.5.0

- composer.json
- composer.lock
- composer/ClassLoader.php
- composer/autoload_classmap.php
- composer/autoload_psr4.php
- composer/autoload_real.php
- composer/autoload_static.php
- composer/installed.json
- composer/installed.php
- psr/clock/LICENSE
- psr/clock/src/ClockInterface.php
- Server PR at https://github.com/nextcloud/server/pull/35872
- OCP PR so it Psalm finds the interface https://github.com/nextcloud-deps/ocp/pull/4
> feat(PSR): ⌚ Add PSR Clock interface as dependency

- .github/workflows/composer-auto.yml
Signed-off-by: Joas Schilling <213943+nickvergessen@users.noreply.github.com>
> chore(autoloader): Make commits instead of amend for clarity

- README.md
Signed-off-by: Joas Schilling <213943+nickvergessen@users.noreply.github.com>
> chore(Readme): Add instructions how to test your PR with server

- .github/workflows/composer-auto.yml
- .github/workflows/composer.yml
> Use supported PHP version for the actions

- .github/workflows/composer.yml
- composer/installed.json
- composer/installed.php
> Enforce to install with --no-dev

- .github/workflows/lint-php.yml
- composer.json
- composer.lock
- composer/installed.json
- composer/installed.php
- guzzlehttp/psr7/src/LazyOpenStream.php
- guzzlehttp/psr7/src/Message.php
- guzzlehttp/psr7/src/MessageTrait.php
- guzzlehttp/psr7/src/ServerRequest.php
> [master] sec(deps): Update guzzlehttp/psr7

- composer.lock
- composer/InstalledVersions.php
- composer/installed.json
- composer/installed.php
- guzzlehttp/psr7/CHANGELOG.md
- guzzlehttp/psr7/README.md
- guzzlehttp/psr7/composer.json
- guzzlehttp/psr7/src/LazyOpenStream.php
- guzzlehttp/psr7/src/Message.php
- guzzlehttp/psr7/src/MessageTrait.php
- guzzlehttp/psr7/src/ServerRequest.php
> [stable25] sec(deps): Update guzzlehttp/psr7

- composer.lock
- composer/ClassLoader.php
- composer/InstalledVersions.php
- composer/autoload_real.php
- composer/installed.json
- composer/installed.php
- guzzlehttp/psr7/CHANGELOG.md
- guzzlehttp/psr7/composer.json
- guzzlehttp/psr7/src/MessageTrait.php
> [stable24] sec(deps): Update guzzlehttp/psr7

- composer.lock
- composer/ClassLoader.php
- composer/InstalledVersions.php
- composer/autoload_real.php
- composer/installed.json
- composer/installed.php
- composer/package-versions-deprecated/src/PackageVersions/Versions.php
- guzzlehttp/psr7/CHANGELOG.md
- guzzlehttp/psr7/composer.json
- guzzlehttp/psr7/src/MessageTrait.php
> [stable22] sec(deps): Update guzzlehttp/psr7

- composer.lock
- composer/ClassLoader.php
- composer/InstalledVersions.php
- composer/autoload_real.php
- composer/installed.json
- composer/installed.php
- guzzlehttp/psr7/CHANGELOG.md
- guzzlehttp/psr7/composer.json
- guzzlehttp/psr7/src/MessageTrait.php
> [stable21] sec(deps): Update guzzlehttp/psr7

- composer.json
- composer.lock
- composer/installed.json
- composer/installed.php
- phpseclib/phpseclib/phpseclib/Crypt/AES.php
- phpseclib/phpseclib/phpseclib/Crypt/Base.php
- phpseclib/phpseclib/phpseclib/Crypt/Blowfish.php
- phpseclib/phpseclib/phpseclib/Crypt/DES.php
- phpseclib/phpseclib/phpseclib/Crypt/Hash.php
- phpseclib/phpseclib/phpseclib/Crypt/RC2.php
- phpseclib/phpseclib/phpseclib/Crypt/RC4.php
- phpseclib/phpseclib/phpseclib/Crypt/RSA.php
- phpseclib/phpseclib/phpseclib/Crypt/Rijndael.php
- phpseclib/phpseclib/phpseclib/File/ASN1.php
- phpseclib/phpseclib/phpseclib/File/X509.php
- phpseclib/phpseclib/phpseclib/Math/BigInteger.php
- phpseclib/phpseclib/phpseclib/Net/SFTP.php
- phpseclib/phpseclib/phpseclib/Net/SSH1.php
- phpseclib/phpseclib/phpseclib/Net/SSH2.php
* Server companion: https://github.com/nextcloud/server/pull/44673
> [stable27] fix(deps): Update phpseclib to 2.0.47

- composer.json
- composer.lock
- composer/installed.php
> [stable30] chore: set version in composer.json

- .github/dependabot.yml
> ci(branchoff): Configure dependabot for stable32
