patches.txt
sabre/xml/lib/Deserializer/functions.php

[stable12] Prevent infinite loop in sabre/xml

---

mcnetic/zipstreamer/src/ZipStreamer.php
patches.txt

[stable12] Patch ZipStreamer to fix directory downloads

---

mcnetic/zipstreamer/src/ZipStreamer.php
patches.txt

Patches ZIpStreamer with https://github.com/McNetic/PHPZipStreamer/pull/39 to fix https://github.com/nextcloud/server/issues/2352

Patch ZipStreamer to fix directory downloads

---

sabre/vobject/lib/Splitter/ICalendar.php
sabre/vobject/lib/Splitter/VCard.php

Fix to silence phan in https://github.com/nextcloud/server/pull/10059

manually patch PHP-Doc of VObject Splitter

---

patches.txt
sabre/vobject/lib/ITip/Broker.php

Ref https://github.com/nextcloud/server/pull/12946 
If DTSTART and/or DTEND and other times are specified with a TZID, some clients
may fail reading the generated iCal data, since the VTIMEZONE definition is
missing.
I dont use Outlook but code make sense :see_no_evil: Backport these changes to `stable15`?

Broker: add timezone to CANCEL messages

---

composer.json
composer.lock
composer/installed.json
sabre/dav/CHANGELOG.md
sabre/dav/lib/DAV/CorePlugin.php
sabre/dav/lib/DAV/Tree.php

[stable14] Bump sabre/dav to 3.2.3

---

.gitignore

This dependency is only required for some tests. Patch make sure that git ~log~ status is not spammed with untracked files.
Need for this test: https://github.com/nextcloud/server/blob/8473a094991dcb8b8a495f65e814edde9a983f08/tests/lib/Files/Type/DetectionTest.php#L135-L137

Add mikey179/vfsstream to gitignore

---

doctrine/dbal/lib/Doctrine/DBAL/SQLParserUtils.php
patches.txt

Needed for https://github.com/nextcloud/server/pull/22118 - working on master because there doctrine/dbal:2.10.2 is used

[stable19] Doctrine: Fix unquoted stmt fragments backslash escaping

---

composer.lock
composer/installed.json
sabre/xml/.gitignore
sabre/xml/CHANGELOG.md
sabre/xml/composer.json
sabre/xml/lib/Reader.php
sabre/xml/lib/Service.php
sabre/xml/lib/Version.php

https://github.com/sabre-io/xml/pull/166 had a regression that was fixed in https://github.com/sabre-io/xml/pull/183
Nextcloud 20 to 19 use v2.2.0. I'll update all stable branches once this has been approved.
For https://github.com/nextcloud/server/issues/22281

Update sabre/xml to fix XML parsing errors (with empty strings)

---

.github/workflows/composer.yml
composer/ClassLoader.php

https://github.com/nextcloud/3rdparty/pull/530 fails with weird composer diffs. Maybe we should use v1 for the old branches.

[stable19] Use composer v1 on CI

---

composer.lock
composer/installed.json
sabre/xml/.gitignore
sabre/xml/CHANGELOG.md
sabre/xml/composer.json
sabre/xml/lib/Reader.php
sabre/xml/lib/Service.php
sabre/xml/lib/Version.php

[stable20] Update sabre/xml to fix XML parsing errors

---

composer/InstalledVersions.php
composer/autoload_classmap.php
composer/autoload_static.php
composer/installed.json
composer/installed.php
symfony/console/Output/TrimmedBufferOutput.php

Add TrimmedBufferOutput.php

---

composer.lock
composer/InstalledVersions.php
composer/installed.json
composer/installed.php
doctrine/event-manager/composer.json

For https://github.com/nextcloud/3rdparty/issues/564, there is no actual code changes.

Bump doctrine/event-manager from 1.1.0 to 1.1.1

---

christophwurst/id3parser/src/getID3/Tags/getid3_id3v2.php
christophwurst/id3parser/src/getID3/getid3_lib.php
composer.json
composer.lock
composer/installed.json
composer/installed.php
composer/package-versions-deprecated/src/PackageVersions/Versions.php

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>
Needed for PHP 8.1 compatibility
Replaces https://github.com/nextcloud/3rdparty/pull/935

Bump christophwurst/id3parser to 0.1.4

---

composer.lock
composer/installed.json
composer/installed.php
composer/package-versions-deprecated/src/PackageVersions/Versions.php
sabre/vobject/lib/Parser/MimeDir.php
sabre/vobject/lib/Property.php
sabre/vobject/lib/Property/Binary.php
sabre/vobject/lib/Property/FloatValue.php
sabre/vobject/lib/Property/ICalendar/CalAddress.php
sabre/vobject/lib/Property/ICalendar/Duration.php
sabre/vobject/lib/Property/ICalendar/Period.php
sabre/vobject/lib/Property/Time.php
sabre/vobject/lib/Property/Uri.php
sabre/vobject/lib/Property/UtcOffset.php
sabre/vobject/lib/Property/VCard/DateAndOrTime.php
sabre/vobject/lib/Property/VCard/TimeStamp.php
sabre/vobject/lib/Recur/EventIterator.php
sabre/vobject/lib/Recur/RDateIterator.php
sabre/vobject/lib/Recur/RRuleIterator.php
sabre/vobject/lib/Version.php

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

Bump sabre/vobject to 4.4.1

---

.github/dependabot.yml

Added a task to https://github.com/nextcloud/server/wiki/Todos-before-a-release as well.

Enable dependabot for stable24

---

christophwurst/id3parser/src/getID3/Tags/getid3_id3v2.php
christophwurst/id3parser/src/getID3/getid3_lib.php
composer.json
composer.lock
composer/installed.json
composer/installed.php

Backport of https://github.com/nextcloud/3rdparty/pull/937
This is needed because it fixes compatibility with PHP 8 which is supported by Nextcloud 21, 22 and 23.

[stable23] Bump christophwurst/id3parser to 0.1.4

---

.github/workflows/lint-php.yml
composer.json
composer.lock
composer/ClassLoader.php
composer/InstalledVersions.php
composer/autoload_real.php
composer/installed.json
composer/installed.php
guzzlehttp/psr7/src/LazyOpenStream.php
guzzlehttp/psr7/src/Message.php
guzzlehttp/psr7/src/MessageTrait.php
guzzlehttp/psr7/src/ServerRequest.php

[stable26] sec(deps): Update guzzlehttp/psr7

---

README.md

Add a note to prevent future developers to specify a wrong version of a package. Is necessary to write the full version number.
Ref: https://github.com/nextcloud/3rdparty/pull/1304#discussion_r1094930891

Improvements at documentation

---

.github/dependabot.yml

We updated all symfony components to 5.x already

No longer ignore symfony 5.x

---

.github/dependabot.yml

We don't update minors on stable branches unless there are security issues, in which case we will notice via other sources but dependabot PRs.
Also configuring symfony to stay on 5.4 LTS for now while we need PHP 8.0 support

fix(CI): Reduce dependabot update-types

---

.github/workflows/composer-auto.yml

In v4 of the action the option changed from `reaction-type` to `reactions`

fix(ci): Bring back reactions on `/composer-update` command

---

composer.json
composer.lock
composer/installed.php

When running dump-autoload, then composer tries to find a matching version number.
Sometimes the VCS detection does not work and the generated version number changes from the commit hash to the fallback and back to the generated version when someone else updates the package.
We are now using a version number in composer.json to avoid a version number ping-pong.

chore: set version in composer.json

---

composer.json
composer.lock
composer/installed.php

When running dump-autoload, then composer tries to find a matching version number.
Sometimes the VCS detection does not work and the generated version number changes from the commit hash to the fallback and back to the generated version when someone else updates the package.
We are now using a version number in composer.json to avoid a version number ping-pong.

[stable29] chore: set version in composer.json

---

composer.json
composer.lock
composer/installed.php

When running dump-autoload, then composer tries to find a matching version number.
Sometimes the VCS detection does not work and the generated version number changes from the commit hash to the fallback and back to the generated version when someone else updates the package.
We are now using a version number in composer.json to avoid a version number ping-pong.

[stable28] chore: set version in composer.json

---

.github/dependabot.yml

- Security updates will be done manually
- Other patch updates are only done on demand

ci: Reduce dependabot config
